-- SQL 고득점 Kit : SUM, MAX, MIN

-- 01 가격이 제일 비싼 식품의 정보 출력하기
--- 방법 1
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

--- 방법 2
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1;


-- 02 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT;


-- 03 최댓값 구하기
--- 방법 1
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1;

--- 방법 2
SELECT MAX(DATETIME) AS 시간
FROM ANIMAL_INS;


-- 04 최솟값 구하기
SELECT MIN(DATETIME) AS 시간
FROM ANIMAL_INS;


-- 05 동물 수 구하기
SELECT COUNT(*) AS 'count'
FROM ANIMAL_INS;


-- 06 중복 제거하기
SELECT COUNT(DISTINCT NAME) AS 'count'
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;
